# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kpopping.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KpopUi(object):
    def setupUi(self, KpopUi):
        KpopUi.setObjectName("KpopUi")
        KpopUi.resize(600, 600)
        KpopUi.setMinimumSize(QtCore.QSize(600, 600))
        KpopUi.setMaximumSize(QtCore.QSize(600, 600))
        self.centralwidget = QtWidgets.QWidget(KpopUi)
        self.centralwidget.setObjectName("centralwidget")
        self.update_button = QtWidgets.QPushButton(self.centralwidget)
        self.update_button.setGeometry(QtCore.QRect(500, 12, 91, 31))
        self.update_button.setObjectName("update_button")
        self.tableWidget_update = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_update.setGeometry(QtCore.QRect(10, 10, 471, 541))
        self.tableWidget_update.setObjectName("tableWidget_update")
        self.tableWidget_update.setColumnCount(1)
        self.tableWidget_update.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_update.setHorizontalHeaderItem(0, item)
        self.close_button = QtWidgets.QPushButton(self.centralwidget)
        self.close_button.setGeometry(QtCore.QRect(500, 512, 91, 31))
        self.close_button.setObjectName("close_button")
        KpopUi.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(KpopUi)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 23))
        self.menubar.setObjectName("menubar")
        KpopUi.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(KpopUi)
        self.statusbar.setObjectName("statusbar")
        KpopUi.setStatusBar(self.statusbar)

        self.retranslateUi(KpopUi)
        self.close_button.clicked.connect(KpopUi.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(KpopUi)

    def retranslateUi(self, KpopUi):
        _translate = QtCore.QCoreApplication.translate
        KpopUi.setWindowTitle(_translate("KpopUi", "Kpopping"))
        self.update_button.setText(_translate("KpopUi", "Update"))
        item = self.tableWidget_update.horizontalHeaderItem(0)
        item.setText(_translate("KpopUi", "链接"))
        self.close_button.setText(_translate("KpopUi", "Close"))
